version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python application.py
    image: website_filter_master_image
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - ./:/project/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - redis

  worker:
    container_name: worker
    # Reuses the image built in the app container
    image: website_filter_master_image
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - ./:/project/
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    image: website_filter_master_image
    command: /start-flower
    volumes:
      - ./:/project/
    env_file:
      - .env
    ports:
      - 5555:5555
    depends_on:
      - redis
      - worker

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
