version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 application:app
    ports:
      - 5000:5000
    env_file:
      - ./.env
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    env_file:
      - ./.env
volumes:
